### ISSUE TITLE
Blank splash sreen

### ISSUE THREAD

**Issue by abolinhas** [triniwiz/nativescript-splashscreen#11]
Hi
I made all the steps for Android
https://www.npmjs.com/package/nativescript-splashscreen#android

But I can't make it work, I always get a blank splash sreen

I use Nativescript 2.3 and my Android version is 6.0.1

My code:
AndroidManifest.xml
`
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="__PACKAGE__"
    android:versionCode="1"
    android:versionName="1.0">

```
<supports-screens
    android:smallScreens="true"
    android:normalScreens="true"
    android:largeScreens="true"
    android:xlargeScreens="true"/>

<uses-sdk
    android:minSdkVersion="17"
    android:targetSdkVersion="__APILEVEL__"/>

<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.INTERNET"/>

<application
    android:name="com.tns.NativeScriptApplication"
    android:allowBackup="true"
    android:icon="@drawable/icon"
    android:label="@string/app_name"
    android:theme="@style/AppTheme" >
    <activity android:name="co.fitcom.SplashScreen" android:noHistory="true">
    <intent-filter>
    <category android:name="android.intent.category.LAUNCHER" />
    <action android:name="android.intent.action.MAIN" />
    </intent-filter>
    </activity>
    <activity
        android:name="com.tns.NativeScriptActivity"
        android:label="@string/title_activity_kimera"
        android:configChanges="keyboardHidden|orientation|screenSize">
    </activity>
    <activity android:name="com.tns.ErrorReportActivity"/>
</application>
```

</manifest>`

SplashScreen.js
`"use strict"
com.viksaa.sssplash.lib.activity.AwesomeSplash.extend("co.fitcom.SplashScreen", {
    initSplash: function (configSplash) {
        /\* you don't need to override every property */

```
    //Customize Circular Reveal
    configSplash.setBackgroundColor(org.nativescript.articamonitor.R.color.md_green_700); //any color you want form colors.xml
    configSplash.setAnimCircularRevealDuration(2000); //int ms
    configSplash.setRevealFlagX(com.viksaa.sssplash.lib.cnst.Flags.REVEAL_RIGHT);  //or Flags.REVEAL_LEFT
    configSplash.setRevealFlagY(com.viksaa.sssplash.lib.cnst.Flags.REVEAL_BOTTOM); //or Flags.REVEAL_TOP


    //Choose LOGO OR PATH; if you don't provide String value for path it's logo by default

    //Customize Logo
    configSplash.setLogoSplash(org.nativescript.articamonitor.R.drawable.splash_logo); //or any other drawable
    configSplash.setAnimLogoSplashDuration(2000); //int ms
    configSplash.setAnimLogoSplashTechnique(com.daimajia.androidanimations.library.Techniques.Bounce); //choose one form Techniques (ref: https://github.com/daimajia/AndroidViewAnimations)



    const title = com.tns.NativeScriptApplication.getInstance().getString(org.nativescript.articamonitor.R.string.splash_title)
    //Customize Title
    configSplash.setTitleSplash(title);
    configSplash.setTitleTextColor(org.nativescript.articamonitor.R.color.md_white);
    configSplash.setTitleTextSize(30);
    configSplash.setAnimTitleDuration(3000); //int ms
    configSplash.setAnimTitleTechnique(com.daimajia.androidanimations.library.Techniques.FlipInX);
    configSplash.setTitleFont("app/fonts/RobotoRegular.ttf"); //provide string to your font located in app/fonts/

},
animationsFinished: function () {
    const intent = new android.content.Intent(com.tns.NativeScriptApplication.getInstance().getApplicationContext(), com.tns.NativeScriptActivity.class)
    intent.addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK);
    com.tns.NativeScriptApplication.getInstance().startActivity(intent);
}
```

});`

splash_settings.xml
`<?xml version="1.0" encoding="utf-8"?>
<resources>
<string name="splash_title">Artica Monitor</string>
</resources>`

Image name /App_Resources/Android/drawable/splash_logo.png

**Comment by abolinhas** [comment]
Hi
I get this error 
com.tns.NativeScriptException: 
Calling js method animationsFinished failed

TypeError: Cannot read property 'class' of undefined
File: "/data/data/org.nativescript.articamonitor/files/app/SplashScreen.js, line: 33, column: 149

StackTrace: 
    Frame: function:'com.viksaa.sssplash.lib.activity.AwesomeSplash.extend.animationsFinished', file:'/data/data/org.nativescript.articamonitor/files/app/SplashScreen.js', line: 33, column: 150

```
at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
at com.tns.Runtime.callJSMethod(Runtime.java:716)
at com.tns.Runtime.callJSMethod(Runtime.java:697)
at com.tns.Runtime.callJSMethod(Runtime.java:687)
at co.fitcom.SplashScreen.animationsFinished(com.viksaa.sssplash.lib.activity.AwesomeSplash.java)
at com.viksaa.sssplash.lib.activity.AwesomeSplash$4.onAnimationEnd(AwesomeSplash.java:214)
at com.nineoldandroids.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:756)
at com.nineoldandroids.animation.ValueAnimator.endAnimation(ValueAnimator.java:1034)
at com.nineoldandroids.animation.ValueAnimator.access$900(ValueAnimator.java:43)
at com.nineoldandroids.animation.ValueAnimator$AnimationHandler.handleMessage(ValueAnimator.java:669)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by triniwiz** [comment]
Fixed https://github.com/triniwiz/nativescript-splashscreen/commit/7faf063e0255b22bbe5810d2e7e52041d4a24495 update to `2.2.0`
